require: 
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - '**/db/**/*'
    - 'bin/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
