require: 
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - '**/db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
  # .html_safe

Style/EmptyMethod:
  Enabled: false
  # def index; end

Metrics/AbcSize:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/Output:
  Enabled: false
