require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - '**/db/schema.rb'
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Output:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# bundle exec rubocop -A
# bundle exec rubocop -a
# bundle exec rubocop -A --only Style/FrozenStringLiteralComment

# Layout/SpaceAroundOperators
# Layout/IndentationWidth
# Layout/IndentationConsistency
# Style/MethodDefParentheses
# Layout/TrailingEmptyLines
# Layout/EmptyLineAfterGuardClause
# Style/RedundantSelf
# Layout/SpaceAfterComma
# Style/FrozenStringLiteralComment
# Layout/EmptyLineAfterMagicComment
# Style/StringLiterals
# Layout/TrailingWhitespace
