require: 
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - '**/db/schema.rb'
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Output:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
  
Lint/UnusedMethodArgument:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

# bundle exec rubocop -A
# bundle exec rubocop -a
# bundle exec rubocop -A --only Style/FrozenStringLiteralComment

# Layout/ClosingParenthesisIndentation
# Layout/FirstArgumentIndentation
# Style/HashSyntax
# Style/ExplicitBlockArgument
  # bad
  # link_to path do
  #   yield
  # end
  # good
  # link_to path, &block
# Layout/SpaceInsidePercentLiteralDelimiters
# Style/TrailingCommaInArrayLiteral
# Layout/EmptyLinesAroundAccessModifier
# Style/NumericLiterals
# Style/OrAssignment
# Layout/EmptyLinesAroundClassBody
# Layout/SpaceAroundOperators
# Style/SymbolArray
# Rails/TimeZone
# Style/TrailingCommaInHashLiteral
# Layout/SpaceInsideHashLiteralBraces
# Layout/IndentationWidth
# Style/IfUnlessModifier
# Layout/IndentationConsistency
# Style/MethodDefParentheses
# Layout/TrailingEmptyLines
# Layout/EmptyLineAfterGuardClause
# Style/RedundantSelf
# Style/UnlessElse
# Layout/SpaceAfterComma
# Style/FrozenStringLiteralComment
# Layout/EmptyLineAfterMagicComment
# Style/StringLiterals
# Layout/TrailingWhitespace
